const testimonials = [
  { src: "/clients/artcaffe.png", tag: "artcaffe recruitment client" },
  { src: "/clients/sweden.png", tag: "sweden recruitment client" },
  { src: "/clients/ireland.png", tag: "ireland recruitment client" },
  { src: "/clients/denmark.png", tag: "denmark recruitment client" },
  { src: "/clients/dutch.png", tag: "dutch recruitment client" },
  { src: "/clients/ctm.png", tag: "ctm recruitment client" },
  { src: "/clients/stanbic.png", tag: "stanbic recruitment client" },
  { src: "/clients/decthlon.png", tag: "decthlon recruitment client" },
  { src: "/clients/aar.png", tag: "aar recruitment client" },
  { src: "/clients/carcare.png", tag: "carcare recruitment client" },
  { src: "/clients/ponty.png", tag: "ponty recruitment client" },
  { src: "/clients/excide.png", tag: "excide recruitment client" },
  { src: "/clients/golden.png", tag: "golden recruitment client" },
  { src: "/clients/ens.png", tag: "ens recruitment client" },
  { src: "/clients/sha2.png", tag: "Self Help Africa recruitment client" },
  { src: "/clients/gc.svg", tag: "gc recruitment client" },
  { src: "/clients/harmony.png", tag: "harmony recruitment client" },
  { src: "/clients/pads.png", tag: "pads recruitment client" },
  { src: "/clients/muigai.png", tag: "muigai recruitment client" },
  { src: "/clients/rianna.png", tag: "rianna recruitment client" },
  { src: "/clients/rochman.png", tag: "rochman recruitment client" },
  { src: "/clients/silent.png", tag: "silent night recruitment client" },
  { src: "/clients/cibo.png", tag: "cibo recruitment client" },
  { src: "/clients/ssn.svg", tag: "ssn recruitment client" },
  {
    src: "/clients/totalsolution.png",
    tag: "totalsolution recruitment client",
  },
  { src: "/clients/quatrix.png", tag: "quatrix recruitment client" },
  { src: "/clients/urban.png", tag: "urban recruitment client" },
  { src: "/clients/alliance.png", tag: "alliance recruitment client" },
];

export default testimonials;
