import Image from 'next/image';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import LinkButton from '@/components/CMS/LinkButton';
import CaseStudyRichText from './CaseStudyRichText';
import { imageUrl } from '@/lib/cms/strapi';
import { CASE_STUDIES_ROUTE } from './CaseStudyCard';

export default function CaseStudyDetail({ study }) {
  return <article className="min-h-screen bg-[#0a0a0a] px-4 pb-20 pt-32 sm:px-6 md:px-12 lg:px-20 lg:pt-40"><div className="container"><Link href={CASE_STUDIES_ROUTE} className="inline-flex items-center gap-2 font-semibold text-[#51D4D6] hover:text-white"><ArrowLeft size={18} /> {study.backLinkLabel}</Link><header className="mt-8 grid items-center gap-10 rounded-3xl border border-white/10 bg-[#1e1e1e] p-5 sm:p-8 lg:grid-cols-2 lg:p-10"><div><p className="font-semibold uppercase tracking-[0.2em] text-[#51D4D6]">{study.service} · {study.industry}</p><h1 className="mt-5 break-words text-3xl font-bold leading-tight text-white sm:text-4xl lg:text-5xl">{study.title}</h1><p className="mt-6 text-lg leading-8 text-gray-300">{study.excerpt}</p>{study.location && <p className="mt-5 text-sm text-gray-400">{study.locationLabel}: {study.location}</p>}</div>{study.heroImage?.src && <Image src={imageUrl(study.heroImage.src)} alt={study.heroImage.alt} width={study.heroImage.width || 800} height={study.heroImage.height || 600} className="h-auto w-full rounded-2xl object-cover" />}</header>{study.metrics?.length > 0 && <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{study.metrics.map((metric) => <div key={`${metric.value}-${metric.label}`} className="rounded-2xl border border-[#51D4D6]/20 bg-[#51D4D6]/5 p-6"><strong className="text-3xl text-white">{metric.value}</strong><p className="mt-2 text-gray-400">{metric.label}</p></div>)}</section>}<div className="mx-auto mt-12 max-w-4xl space-y-10">{study.sections?.map((section) => <section key={section.heading}><h2 className="break-words text-2xl font-bold text-white sm:text-3xl">{section.heading}</h2><CaseStudyRichText>{section.body}</CaseStudyRichText></section>)}{study.showClientQuotation === true && study.testimonial?.quote && <blockquote className="rounded-2xl border-l-4 border-[#51D4D6] bg-[#1e1e1e] p-7"><p className="text-xl italic leading-8 text-white">“{study.testimonial.quote}”</p><footer className="mt-4 text-gray-400">{[study.testimonial.name, study.testimonial.role, study.testimonial.company, study.clientName].filter(Boolean)[0]}</footer></blockquote>}<div className="pt-4"><LinkButton link={study.cta} /></div></div></div></article>;
}
